#!/bin/sh -e

rm -f got

../logmerge ../samples/* > got

if ! cmp expected got
then
	echo "Failed with files as args."
	ls -l ../logmerge got ../samples/*
	exit 1
fi

rm -f got

# Test again with files from stdin

ls -1 ../samples/* | ../logmerge > got 2> /dev/null

if ! cmp expected got
then
	echo "Failed with files from stdin."
	exit 1
fi

rm -f got
