name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Boost
      id: boost
      uses: mickem/build-boost@v1
      with:
        version: 1.71.0
        libraries: iostreams filesystem regex
        platform: x64
        configuration: Release
    - name: make
      run: make
    - name: test
      run: make test
