name: CI

on:
  push:
    branches: [ zig ]
  pull_request:
    branches: [ zig ]

jobs:
  build:
    name: Build with ${{matrix.zig_version}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        zig_version: ["0.14.1", "master"]
        os: ["ubuntu-latest", "macos-latest", "ubuntu-24.04-arm"]

    steps:      
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev clang

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}

      - name: Build project
        shell: bash
        run: zig build

      - name: Run tests
        run: zig build test --summary all
